version: '3.8'

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongodata/:/data/db"

  monk-service:
    build:
      dockerfile: media.dockerfile
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - mongodb

networks:
  default:
    # Use a custom driver
    driver: bridge